### ISSUE TITLE
Recent discord update broke this plugin

### ISSUE THREAD

**Issue by NekoBlek** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#17]
Then again, the recent update broke a looooot of plugins, even most the default ones that come with enhanced discord. Deleted messages don't stay anymore.

**Comment by NekoBlek** [comment]
if you're reading this, and you're on the newest version and you can confirm that it still work, please let me know.

**Comment by ghost** [comment]
On bagedBD it doesn't turn red but does stay

**Comment by Hiroshi18** [comment]
It was fixed on this PR https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/pull/18 made by ShiiroSan

You could manually use it manually for now till the maintainer accept the PR

Go to your plugin folder and copy and paste the code in https://github.com/ShiiroSan/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/NoDeleteMessages.plugin.js to you local plugin file NoDeleteMessages.plugin.js t

**Comment by NekoBlek** [comment]
thank you so much! However I tested it, and it still does not work. Is there something I should do to refresh it, or ensure it works properly?

**Comment by Hiroshi18** [comment]
Reload your plugins. There should be a option there in the plug-in tab or restart the   discord

**Comment by Hiroshi18** [comment]
Also there could a problem with custom themes

**Comment by rakion99** [comment]
i just updated to that PR and works fine again thanks i forgot to check pull request till i saw this issue lol

**Comment by NekoBlek** [comment]
yee, whenever I update plugins, I delete the old one, reload discord, add the new plugin, and then reload again. Also, tried removing the plugin repo, theme repo, and plugin repo settings because they never worked properly anyway. Still doesn't work. :/

**Comment by Hiroshi18** [comment]
Maybe try deactivating all plugins and letting only this one activated or reinstalling better discord

**Comment by NekoBlek** [comment]
I'll give it a try

**Comment by Hiroshi18** [comment]
Alright, It worked?

**Comment by NekoBlek** [comment]
Nope, unfortunately nothing seems to fix it. Even when I first started using it, the plugin was always weird. It worked sometimes, but also sometimes it didn't. Whenever I do have it installed it breaks the sliders, and the reload buttons. Well, it breaks almost everything in terms of the plugin settings.

**Comment by ShiiroSan** [comment]
Fixed by #18
